platform :android do
    lane :upload_aab do |options|
      _track = options[:track]
      _aab = options[:aab]
    
      upload_to_play_store(
        track: _track,
        rollout: '1.0',
        aab: _aab,
        skip_upload_metadata: 'true',
        skip_upload_changelogs: 'true',
        skip_upload_images: 'true',
        skip_upload_screenshots: 'true'
      )
    end
    
    lane :upload_metadata do |options|
      _track = options[:track]
      _changesNotSentForReview = options[:send_to_review] ? 'false' : 'true'
    
      upload_to_play_store(
        track: _track,
        skip_upload_apk: 'true',
        skip_upload_aab: 'true',
        skip_upload_metadata: 'false',
        skip_upload_changelogs: 'true',
        skip_upload_images: 'true',
        skip_upload_screenshots: 'true',
        changes_not_sent_for_review: _changesNotSentForReview
      )
    end
    
    lane :upload_changelogs do |options|
      _track = options[:track]
      _changesNotSentForReview = options[:send_to_review] ? 'false' : 'true'
    
      upload_to_play_store(
        track: _track,
        skip_upload_apk: 'true',
        skip_upload_aab: 'true',
        skip_upload_metadata: 'true',
        skip_upload_changelogs: 'false',
        skip_upload_images: 'true',
        skip_upload_screenshots: 'true',
        changes_not_sent_for_review: _changesNotSentForReview
      )
    end
    
    lane :upload_images do |options|
      _track = options[:track]
      _changesNotSentForReview = options[:send_to_review] ? 'false' : 'true'
    
      upload_to_play_store(
        track: _track,
        skip_upload_apk: 'true',
        skip_upload_aab: 'true',
        skip_upload_metadata: 'true',
        skip_upload_changelogs: 'true',
        skip_upload_images: 'false',
        skip_upload_screenshots: 'true',
        changes_not_sent_for_review: _changesNotSentForReview
      )
    end
    
    lane :upload_screenshots do |options|
      _track = options[:track]
      _changesNotSentForReview = options[:send_to_review] ? 'false' : 'true'
    
      upload_to_play_store(
        track: _track,
        skip_upload_apk: 'true',
        skip_upload_aab: 'true',
        skip_upload_metadata: 'true',
        skip_upload_changelogs: 'true',
        skip_upload_images: 'true',
        skip_upload_screenshots: 'false',
        changes_not_sent_for_review: _changesNotSentForReview
      )
    end
end

platform :ios do
    lane :upload_ipa do |options|
      
    end
    
    lane :upload_metadata do |options|
      
    end
    
    lane :upload_changelogs do |options|
      
    end
    
    lane :upload_images do |options|
      
    end
    
    lane :upload_screenshots do |options|
      
    end
end